INSERT INTO part (name, weight) VALUES ('Anchor',262);
INSERT INTO part (name, weight) VALUES ('Deck',280);
INSERT INTO part (name, weight) VALUES ('Lower Back',280);
INSERT INTO part (name, weight) VALUES ('Steam',246);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',224);
INSERT INTO part (name, weight) VALUES ('Steam',280);
INSERT INTO part (name, weight) VALUES ('Tail',274);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Lower Back',211);
INSERT INTO part (name, weight) VALUES ('Lower Back',167);
INSERT INTO part (name, weight) VALUES ('Upper Tail',167);
INSERT INTO part (name, weight) VALUES ('Head',293);
INSERT INTO part (name, weight) VALUES ('Lower Back',293);
INSERT INTO part (name, weight) VALUES ('Upper Tail',173);
INSERT INTO part (name, weight) VALUES ('Tail',246);
INSERT INTO part (name, weight) VALUES ('Steam',274);
INSERT INTO part (name, weight) VALUES ('Upper Tail',265);
INSERT INTO part (name, weight) VALUES ('Deck',223);
INSERT INTO part (name, weight) VALUES ('Bow',211);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Anchor',262);
INSERT INTO part (name, weight) VALUES ('Bow',223);
INSERT INTO part (name, weight) VALUES ('Head',280);
INSERT INTO part (name, weight) VALUES ('Tail',257);
INSERT INTO part (name, weight) VALUES ('Propeller',167);
INSERT INTO part (name, weight) VALUES ('Hull',211);
INSERT INTO part (name, weight) VALUES ('Forward',186);
INSERT INTO part (name, weight) VALUES ('Tail',237);
INSERT INTO part (name, weight) VALUES ('Left Wing',211);
INSERT INTO part (name, weight) VALUES ('Propeller',265);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Funnel',223);
INSERT INTO part (name, weight) VALUES ('Bow',262);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Propeller',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Propeller',257);
INSERT INTO part (name, weight) VALUES ('Funnel',274);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',293);
INSERT INTO part (name, weight) VALUES ('Right Wing',173);
INSERT INTO part (name, weight) VALUES ('Deck',211);
INSERT INTO part (name, weight) VALUES ('Propeller',257);
INSERT INTO part (name, weight) VALUES ('Bow',186);
INSERT INTO part (name, weight) VALUES ('Right Wing',293);
INSERT INTO part (name, weight) VALUES ('Deck',173);
INSERT INTO part (name, weight) VALUES ('Funnel',257);
INSERT INTO part (name, weight) VALUES ('Head',186);
INSERT INTO part (name, weight) VALUES ('Deck',257);
INSERT INTO part (name, weight) VALUES ('Upper Tail',223);
INSERT INTO part (name, weight) VALUES ('Upper Back',173);
INSERT INTO part (name, weight) VALUES ('Anchor',224);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',224);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Steam',211);
INSERT INTO part (name, weight) VALUES ('Forward',246);
INSERT INTO part (name, weight) VALUES ('Deck',237);
INSERT INTO part (name, weight) VALUES ('Propeller',167);
INSERT INTO part (name, weight) VALUES ('Right Wing',257);
INSERT INTO part (name, weight) VALUES ('Head',293);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Deck',224);
INSERT INTO part (name, weight) VALUES ('Lower Back',211);
INSERT INTO part (name, weight) VALUES ('Upper Back',265);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Forward',167);
INSERT INTO part (name, weight) VALUES ('Right Wing',167);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Upper Tail',167);
INSERT INTO part (name, weight) VALUES ('Anchor',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',257);
INSERT INTO part (name, weight) VALUES ('Lower Back',173);
INSERT INTO part (name, weight) VALUES ('Left Wing',265);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',274);
INSERT INTO part (name, weight) VALUES ('Right Wing',224);
INSERT INTO part (name, weight) VALUES ('Left Wing',274);
INSERT INTO part (name, weight) VALUES ('Propeller',274);
INSERT INTO part (name, weight) VALUES ('Tail',280);
INSERT INTO part (name, weight) VALUES ('Upper Tail',237);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Hull',293);
INSERT INTO part (name, weight) VALUES ('Deck',262);
INSERT INTO part (name, weight) VALUES ('Funnel',167);
INSERT INTO part (name, weight) VALUES ('Steam',173);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Head',173);
INSERT INTO part (name, weight) VALUES ('Bow',246);
INSERT INTO part (name, weight) VALUES ('Anchor',173);
INSERT INTO part (name, weight) VALUES ('Hull',211);
INSERT INTO part (name, weight) VALUES ('Head',173);
INSERT INTO part (name, weight) VALUES ('Propeller',224);
INSERT INTO part (name, weight) VALUES ('Right Wing',262);
INSERT INTO part (name, weight) VALUES ('Lower Back',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',211);
INSERT INTO part (name, weight) VALUES ('Head',211);
INSERT INTO part (name, weight) VALUES ('Right Wing',173);
INSERT INTO part (name, weight) VALUES ('Deck',167);
INSERT INTO part (name, weight) VALUES ('Bow',224);
INSERT INTO part (name, weight) VALUES ('Forward',265);
INSERT INTO part (name, weight) VALUES ('Tail',280);
INSERT INTO part (name, weight) VALUES ('Steam',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',257);
INSERT INTO part (name, weight) VALUES ('Head',274);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Funnel',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',262);
INSERT INTO part (name, weight) VALUES ('Upper Back',265);
INSERT INTO part (name, weight) VALUES ('Funnel',237);
INSERT INTO part (name, weight) VALUES ('Hull',186);
INSERT INTO part (name, weight) VALUES ('Hull',274);
INSERT INTO part (name, weight) VALUES ('Propeller',262);
INSERT INTO part (name, weight) VALUES ('Bow',280);
INSERT INTO part (name, weight) VALUES ('Lower Back',246);
INSERT INTO part (name, weight) VALUES ('Steam',293);
INSERT INTO part (name, weight) VALUES ('Bow',224);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
INSERT INTO part (name, weight) VALUES ('Propeller',293);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Forward',265);
INSERT INTO part (name, weight) VALUES ('Upper Tail',293);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Right Wing',211);
INSERT INTO part (name, weight) VALUES ('Anchor',211);
INSERT INTO part (name, weight) VALUES ('Tail',173);
INSERT INTO part (name, weight) VALUES ('Upper Back',280);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',262);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Head',274);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',237);
INSERT INTO part (name, weight) VALUES ('Tail',173);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Hull',224);
INSERT INTO part (name, weight) VALUES ('Propeller',237);
INSERT INTO part (name, weight) VALUES ('Steam',280);
INSERT INTO part (name, weight) VALUES ('Anchor',262);
INSERT INTO part (name, weight) VALUES ('Forward',173);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',293);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Bow',223);
INSERT INTO part (name, weight) VALUES ('Hull',274);
INSERT INTO part (name, weight) VALUES ('Bow',257);
INSERT INTO part (name, weight) VALUES ('Hull',262);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Hull',262);
INSERT INTO part (name, weight) VALUES ('Head',237);
INSERT INTO part (name, weight) VALUES ('Hull',173);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Lower Back',173);
INSERT INTO part (name, weight) VALUES ('Steam',274);
INSERT INTO part (name, weight) VALUES ('Steam',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',223);
INSERT INTO part (name, weight) VALUES ('Upper Back',246);
INSERT INTO part (name, weight) VALUES ('Left Wing',293);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Anchor',237);
INSERT INTO part (name, weight) VALUES ('Steam',173);
INSERT INTO part (name, weight) VALUES ('Forward',167);
INSERT INTO part (name, weight) VALUES ('Hull',280);
INSERT INTO part (name, weight) VALUES ('Propeller',237);
INSERT INTO part (name, weight) VALUES ('Lower Back',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
INSERT INTO part (name, weight) VALUES ('Forward',223);
INSERT INTO part (name, weight) VALUES ('Right Wing',167);
INSERT INTO part (name, weight) VALUES ('Steam',293);
INSERT INTO part (name, weight) VALUES ('Forward',237);
INSERT INTO part (name, weight) VALUES ('Upper Back',224);
INSERT INTO part (name, weight) VALUES ('Bow',280);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Forward',246);
INSERT INTO part (name, weight) VALUES ('Funnel',237);
INSERT INTO part (name, weight) VALUES ('Bow',246);
INSERT INTO part (name, weight) VALUES ('Left Wing',262);
INSERT INTO part (name, weight) VALUES ('Forward',211);
INSERT INTO part (name, weight) VALUES ('Lower Back',223);
INSERT INTO part (name, weight) VALUES ('Bow',224);
INSERT INTO part (name, weight) VALUES ('Forward',274);
INSERT INTO part (name, weight) VALUES ('Funnel',173);
INSERT INTO part (name, weight) VALUES ('Propeller',237);
INSERT INTO part (name, weight) VALUES ('Head',274);
INSERT INTO part (name, weight) VALUES ('Left Wing',167);
INSERT INTO part (name, weight) VALUES ('Funnel',223);
INSERT INTO part (name, weight) VALUES ('Left Wing',246);
INSERT INTO part (name, weight) VALUES ('Propeller',265);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',173);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Lower Back',246);
INSERT INTO part (name, weight) VALUES ('Upper Tail',211);
INSERT INTO part (name, weight) VALUES ('Propeller',262);
INSERT INTO part (name, weight) VALUES ('Propeller',262);
INSERT INTO part (name, weight) VALUES ('Lower Back',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',262);
INSERT INTO part (name, weight) VALUES ('Left Wing',211);
INSERT INTO part (name, weight) VALUES ('Propeller',223);
INSERT INTO part (name, weight) VALUES ('Upper Tail',265);
INSERT INTO part (name, weight) VALUES ('Hull',280);
INSERT INTO part (name, weight) VALUES ('Funnel',265);
INSERT INTO part (name, weight) VALUES ('Left Wing',280);
INSERT INTO part (name, weight) VALUES ('Deck',224);
INSERT INTO part (name, weight) VALUES ('Funnel',274);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Head',223);
INSERT INTO part (name, weight) VALUES ('Steam',257);
INSERT INTO part (name, weight) VALUES ('Upper Tail',173);
INSERT INTO part (name, weight) VALUES ('Lower Back',167);
INSERT INTO part (name, weight) VALUES ('Upper Tail',173);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Lower Back',293);
INSERT INTO part (name, weight) VALUES ('Propeller',280);
INSERT INTO part (name, weight) VALUES ('Funnel',223);
INSERT INTO part (name, weight) VALUES ('Steam',265);
INSERT INTO part (name, weight) VALUES ('Lower Back',173);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Propeller',211);
INSERT INTO part (name, weight) VALUES ('Head',274);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Anchor',262);
INSERT INTO part (name, weight) VALUES ('Propeller',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',237);
INSERT INTO part (name, weight) VALUES ('Propeller',211);
INSERT INTO part (name, weight) VALUES ('Bow',223);
INSERT INTO part (name, weight) VALUES ('Tail',223);
INSERT INTO part (name, weight) VALUES ('Bow',173);
INSERT INTO part (name, weight) VALUES ('Right Wing',224);
INSERT INTO part (name, weight) VALUES ('Funnel',167);
INSERT INTO part (name, weight) VALUES ('Left Wing',237);
INSERT INTO part (name, weight) VALUES ('Bow',280);
INSERT INTO part (name, weight) VALUES ('Tail',211);
INSERT INTO part (name, weight) VALUES ('Right Wing',262);
INSERT INTO part (name, weight) VALUES ('Upper Back',224);
INSERT INTO part (name, weight) VALUES ('Upper Back',293);
INSERT INTO part (name, weight) VALUES ('Steam',167);
INSERT INTO part (name, weight) VALUES ('Steam',293);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Deck',293);
INSERT INTO part (name, weight) VALUES ('Head',280);
INSERT INTO part (name, weight) VALUES ('Anchor',265);
INSERT INTO part (name, weight) VALUES ('Forward',211);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Forward',186);
INSERT INTO part (name, weight) VALUES ('Funnel',280);
INSERT INTO part (name, weight) VALUES ('Bow',274);
INSERT INTO part (name, weight) VALUES ('Steam',211);
INSERT INTO part (name, weight) VALUES ('Left Wing',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',293);
INSERT INTO part (name, weight) VALUES ('Head',246);
INSERT INTO part (name, weight) VALUES ('Tail',265);
INSERT INTO part (name, weight) VALUES ('Right Wing',167);
INSERT INTO part (name, weight) VALUES ('Propeller',280);
INSERT INTO part (name, weight) VALUES ('Bow',257);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Propeller',280);
INSERT INTO part (name, weight) VALUES ('Lower Back',173);
INSERT INTO part (name, weight) VALUES ('Right Wing',274);
INSERT INTO part (name, weight) VALUES ('Funnel',265);
INSERT INTO part (name, weight) VALUES ('Head',262);
INSERT INTO part (name, weight) VALUES ('Forward',223);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Forward',257);
INSERT INTO part (name, weight) VALUES ('Propeller',274);
INSERT INTO part (name, weight) VALUES ('Deck',265);
INSERT INTO part (name, weight) VALUES ('Hull',293);
INSERT INTO part (name, weight) VALUES ('Deck',262);
INSERT INTO part (name, weight) VALUES ('Upper Tail',280);
INSERT INTO part (name, weight) VALUES ('Tail',224);
INSERT INTO part (name, weight) VALUES ('Tail',262);
INSERT INTO part (name, weight) VALUES ('Head',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Deck',246);
INSERT INTO part (name, weight) VALUES ('Funnel',237);
INSERT INTO part (name, weight) VALUES ('Propeller',173);
INSERT INTO part (name, weight) VALUES ('Hull',257);
INSERT INTO part (name, weight) VALUES ('Upper Tail',262);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Right Wing',211);
INSERT INTO part (name, weight) VALUES ('Steam',274);
INSERT INTO part (name, weight) VALUES ('Left Wing',257);
INSERT INTO part (name, weight) VALUES ('Upper Tail',173);
INSERT INTO part (name, weight) VALUES ('Bow',246);
INSERT INTO part (name, weight) VALUES ('Bow',211);
INSERT INTO part (name, weight) VALUES ('Right Wing',274);
INSERT INTO part (name, weight) VALUES ('Left Wing',167);
INSERT INTO part (name, weight) VALUES ('Steam',265);
INSERT INTO part (name, weight) VALUES ('Hull',246);
INSERT INTO part (name, weight) VALUES ('Anchor',211);
INSERT INTO part (name, weight) VALUES ('Head',224);
INSERT INTO part (name, weight) VALUES ('Left Wing',223);
INSERT INTO part (name, weight) VALUES ('Lower Back',257);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Steam',262);
INSERT INTO part (name, weight) VALUES ('Forward',211);
INSERT INTO part (name, weight) VALUES ('Right Wing',237);
INSERT INTO part (name, weight) VALUES ('Head',265);
INSERT INTO part (name, weight) VALUES ('Anchor',211);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Propeller',257);
INSERT INTO part (name, weight) VALUES ('Left Wing',167);
INSERT INTO part (name, weight) VALUES ('Anchor',274);
INSERT INTO part (name, weight) VALUES ('Propeller',257);
INSERT INTO part (name, weight) VALUES ('Anchor',274);
INSERT INTO part (name, weight) VALUES ('Anchor',274);
INSERT INTO part (name, weight) VALUES ('Head',186);
INSERT INTO part (name, weight) VALUES ('Forward',167);
INSERT INTO part (name, weight) VALUES ('Upper Back',274);
INSERT INTO part (name, weight) VALUES ('Anchor',173);
INSERT INTO part (name, weight) VALUES ('Funnel',293);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Steam',237);
INSERT INTO part (name, weight) VALUES ('Funnel',167);
INSERT INTO part (name, weight) VALUES ('Propeller',293);
INSERT INTO part (name, weight) VALUES ('Steam',167);
INSERT INTO part (name, weight) VALUES ('Left Wing',223);
INSERT INTO part (name, weight) VALUES ('Forward',237);
INSERT INTO part (name, weight) VALUES ('Anchor',224);
INSERT INTO part (name, weight) VALUES ('Bow',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',274);
INSERT INTO part (name, weight) VALUES ('Funnel',246);
INSERT INTO part (name, weight) VALUES ('Funnel',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Funnel',257);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Propeller',274);
INSERT INTO part (name, weight) VALUES ('Anchor',211);
INSERT INTO part (name, weight) VALUES ('Upper Tail',262);
INSERT INTO part (name, weight) VALUES ('Upper Tail',265);
INSERT INTO part (name, weight) VALUES ('Head',167);
INSERT INTO part (name, weight) VALUES ('Head',224);
INSERT INTO part (name, weight) VALUES ('Upper Tail',173);
INSERT INTO part (name, weight) VALUES ('Funnel',262);
INSERT INTO part (name, weight) VALUES ('Upper Back',262);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Bow',223);
INSERT INTO part (name, weight) VALUES ('Right Wing',274);
INSERT INTO part (name, weight) VALUES ('Funnel',173);
INSERT INTO part (name, weight) VALUES ('Lower Back',237);
INSERT INTO part (name, weight) VALUES ('Upper Tail',237);
INSERT INTO part (name, weight) VALUES ('Upper Back',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',173);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Anchor',265);
INSERT INTO part (name, weight) VALUES ('Left Wing',265);
INSERT INTO part (name, weight) VALUES ('Left Wing',237);
INSERT INTO part (name, weight) VALUES ('Bow',173);
INSERT INTO part (name, weight) VALUES ('Deck',173);
INSERT INTO part (name, weight) VALUES ('Upper Back',237);
INSERT INTO part (name, weight) VALUES ('Lower Back',186);
INSERT INTO part (name, weight) VALUES ('Propeller',211);
INSERT INTO part (name, weight) VALUES ('Upper Tail',237);
INSERT INTO part (name, weight) VALUES ('Hull',167);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Bow',237);
INSERT INTO part (name, weight) VALUES ('Steam',224);
INSERT INTO part (name, weight) VALUES ('Steam',224);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',274);
INSERT INTO part (name, weight) VALUES ('Head',262);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Tail',211);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Funnel',280);
INSERT INTO part (name, weight) VALUES ('Forward',224);
INSERT INTO part (name, weight) VALUES ('Anchor',265);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Funnel',237);
INSERT INTO part (name, weight) VALUES ('Funnel',257);
INSERT INTO part (name, weight) VALUES ('Deck',173);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Right Wing',280);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Steam',237);
INSERT INTO part (name, weight) VALUES ('Right Wing',237);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Right Wing',265);
INSERT INTO part (name, weight) VALUES ('Head',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
INSERT INTO part (name, weight) VALUES ('Head',173);
INSERT INTO part (name, weight) VALUES ('Upper Tail',211);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Funnel',246);
INSERT INTO part (name, weight) VALUES ('Deck',173);
INSERT INTO part (name, weight) VALUES ('Bow',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',224);
INSERT INTO part (name, weight) VALUES ('Upper Tail',167);
INSERT INTO part (name, weight) VALUES ('Hull',224);
INSERT INTO part (name, weight) VALUES ('Bow',262);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Bow',224);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Tail',274);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Anchor',237);
INSERT INTO part (name, weight) VALUES ('Funnel',274);
INSERT INTO part (name, weight) VALUES ('Steam',237);
INSERT INTO part (name, weight) VALUES ('Upper Tail',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',280);
INSERT INTO part (name, weight) VALUES ('Forward',186);
INSERT INTO part (name, weight) VALUES ('Steam',211);
INSERT INTO part (name, weight) VALUES ('Forward',265);
INSERT INTO part (name, weight) VALUES ('Steam',265);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Upper Tail',223);
INSERT INTO part (name, weight) VALUES ('Funnel',265);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Deck',211);
INSERT INTO part (name, weight) VALUES ('Tail',280);
INSERT INTO part (name, weight) VALUES ('Funnel',167);
INSERT INTO part (name, weight) VALUES ('Steam',173);
INSERT INTO part (name, weight) VALUES ('Tail',173);
INSERT INTO part (name, weight) VALUES ('Right Wing',224);
INSERT INTO part (name, weight) VALUES ('Right Wing',223);
INSERT INTO part (name, weight) VALUES ('Head',167);
INSERT INTO part (name, weight) VALUES ('Tail',237);
INSERT INTO part (name, weight) VALUES ('Deck',280);
INSERT INTO part (name, weight) VALUES ('Tail',173);
INSERT INTO part (name, weight) VALUES ('Bow',262);
INSERT INTO part (name, weight) VALUES ('Hull',246);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Tail',237);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Hull',167);
INSERT INTO part (name, weight) VALUES ('Forward',265);
INSERT INTO part (name, weight) VALUES ('Bow',186);
INSERT INTO part (name, weight) VALUES ('Deck',246);
INSERT INTO part (name, weight) VALUES ('Forward',262);
INSERT INTO part (name, weight) VALUES ('Tail',223);
INSERT INTO part (name, weight) VALUES ('Lower Back',265);
INSERT INTO part (name, weight) VALUES ('Head',224);
INSERT INTO part (name, weight) VALUES ('Upper Back',173);
INSERT INTO part (name, weight) VALUES ('Anchor',224);
INSERT INTO part (name, weight) VALUES ('Bow',223);
INSERT INTO part (name, weight) VALUES ('Forward',173);
INSERT INTO part (name, weight) VALUES ('Bow',167);
INSERT INTO part (name, weight) VALUES ('Right Wing',223);
INSERT INTO part (name, weight) VALUES ('Funnel',293);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Deck',293);
INSERT INTO part (name, weight) VALUES ('Bow',274);
INSERT INTO part (name, weight) VALUES ('Head',274);
INSERT INTO part (name, weight) VALUES ('Propeller',265);
INSERT INTO part (name, weight) VALUES ('Upper Back',274);
INSERT INTO part (name, weight) VALUES ('Lower Back',211);
INSERT INTO part (name, weight) VALUES ('Anchor',237);
INSERT INTO part (name, weight) VALUES ('Head',237);
INSERT INTO part (name, weight) VALUES ('Upper Tail',262);
INSERT INTO part (name, weight) VALUES ('Right Wing',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',167);
INSERT INTO part (name, weight) VALUES ('Propeller',257);
INSERT INTO part (name, weight) VALUES ('Tail',211);
INSERT INTO part (name, weight) VALUES ('Tail',274);
INSERT INTO part (name, weight) VALUES ('Right Wing',262);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Upper Back',293);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Head',224);
INSERT INTO part (name, weight) VALUES ('Right Wing',280);
INSERT INTO part (name, weight) VALUES ('Propeller',262);
INSERT INTO part (name, weight) VALUES ('Tail',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',186);
INSERT INTO part (name, weight) VALUES ('Right Wing',262);
INSERT INTO part (name, weight) VALUES ('Upper Back',223);
INSERT INTO part (name, weight) VALUES ('Bow',173);
INSERT INTO part (name, weight) VALUES ('Right Wing',223);
INSERT INTO part (name, weight) VALUES ('Head',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',262);
INSERT INTO part (name, weight) VALUES ('Forward',223);
INSERT INTO part (name, weight) VALUES ('Left Wing',211);
INSERT INTO part (name, weight) VALUES ('Anchor',186);
INSERT INTO part (name, weight) VALUES ('Propeller',274);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Steam',257);
INSERT INTO part (name, weight) VALUES ('Head',173);
INSERT INTO part (name, weight) VALUES ('Hull',186);
INSERT INTO part (name, weight) VALUES ('Propeller',293);
INSERT INTO part (name, weight) VALUES ('Funnel',167);
INSERT INTO part (name, weight) VALUES ('Upper Back',211);
INSERT INTO part (name, weight) VALUES ('Deck',246);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Head',211);
INSERT INTO part (name, weight) VALUES ('Hull',186);
INSERT INTO part (name, weight) VALUES ('Bow',246);
INSERT INTO part (name, weight) VALUES ('Tail',280);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Anchor',246);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Lower Back',237);
INSERT INTO part (name, weight) VALUES ('Bow',211);
INSERT INTO part (name, weight) VALUES ('Upper Tail',237);
INSERT INTO part (name, weight) VALUES ('Forward',237);
INSERT INTO part (name, weight) VALUES ('Lower Back',246);
INSERT INTO part (name, weight) VALUES ('Head',173);
INSERT INTO part (name, weight) VALUES ('Head',223);
INSERT INTO part (name, weight) VALUES ('Deck',173);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Bow',237);
INSERT INTO part (name, weight) VALUES ('Anchor',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',223);
INSERT INTO part (name, weight) VALUES ('Bow',293);
INSERT INTO part (name, weight) VALUES ('Head',262);
INSERT INTO part (name, weight) VALUES ('Upper Back',274);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Upper Back',246);
INSERT INTO part (name, weight) VALUES ('Left Wing',237);
INSERT INTO part (name, weight) VALUES ('Head',246);
INSERT INTO part (name, weight) VALUES ('Tail',211);
INSERT INTO part (name, weight) VALUES ('Upper Tail',257);
INSERT INTO part (name, weight) VALUES ('Upper Back',265);
INSERT INTO part (name, weight) VALUES ('Bow',274);
INSERT INTO part (name, weight) VALUES ('Anchor',224);
INSERT INTO part (name, weight) VALUES ('Upper Back',262);
INSERT INTO part (name, weight) VALUES ('Right Wing',224);
INSERT INTO part (name, weight) VALUES ('Left Wing',262);
INSERT INTO part (name, weight) VALUES ('Upper Back',274);
INSERT INTO part (name, weight) VALUES ('Propeller',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',211);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Upper Back',223);
INSERT INTO part (name, weight) VALUES ('Upper Back',265);
INSERT INTO part (name, weight) VALUES ('Bow',186);
INSERT INTO part (name, weight) VALUES ('Bow',257);
INSERT INTO part (name, weight) VALUES ('Propeller',173);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Lower Back',274);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Right Wing',167);
INSERT INTO part (name, weight) VALUES ('Right Wing',280);
INSERT INTO part (name, weight) VALUES ('Right Wing',224);
INSERT INTO part (name, weight) VALUES ('Head',173);
INSERT INTO part (name, weight) VALUES ('Forward',167);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Upper Back',293);
INSERT INTO part (name, weight) VALUES ('Anchor',274);
INSERT INTO part (name, weight) VALUES ('Upper Tail',280);
INSERT INTO part (name, weight) VALUES ('Head',274);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Anchor',237);
INSERT INTO part (name, weight) VALUES ('Right Wing',293);
INSERT INTO part (name, weight) VALUES ('Right Wing',280);
INSERT INTO part (name, weight) VALUES ('Anchor',167);
INSERT INTO part (name, weight) VALUES ('Steam',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',237);
INSERT INTO part (name, weight) VALUES ('Left Wing',265);
INSERT INTO part (name, weight) VALUES ('Head',224);
INSERT INTO part (name, weight) VALUES ('Lower Back',262);
INSERT INTO part (name, weight) VALUES ('Anchor',224);
INSERT INTO part (name, weight) VALUES ('Anchor',262);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Lower Back',223);
INSERT INTO part (name, weight) VALUES ('Lower Back',265);
INSERT INTO part (name, weight) VALUES ('Upper Back',265);
INSERT INTO part (name, weight) VALUES ('Deck',211);
INSERT INTO part (name, weight) VALUES ('Steam',237);
INSERT INTO part (name, weight) VALUES ('Deck',173);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Anchor',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',167);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Tail',237);
INSERT INTO part (name, weight) VALUES ('Right Wing',223);
INSERT INTO part (name, weight) VALUES ('Head',223);
INSERT INTO part (name, weight) VALUES ('Lower Back',186);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Lower Back',246);
INSERT INTO part (name, weight) VALUES ('Right Wing',167);
INSERT INTO part (name, weight) VALUES ('Hull',167);
INSERT INTO part (name, weight) VALUES ('Hull',186);
INSERT INTO part (name, weight) VALUES ('Forward',224);
INSERT INTO part (name, weight) VALUES ('Steam',167);
INSERT INTO part (name, weight) VALUES ('Steam',274);
INSERT INTO part (name, weight) VALUES ('Propeller',293);
INSERT INTO part (name, weight) VALUES ('Hull',224);
INSERT INTO part (name, weight) VALUES ('Tail',246);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Deck',237);
INSERT INTO part (name, weight) VALUES ('Funnel',246);
INSERT INTO part (name, weight) VALUES ('Deck',246);
INSERT INTO part (name, weight) VALUES ('Left Wing',293);
INSERT INTO part (name, weight) VALUES ('Forward',265);
INSERT INTO part (name, weight) VALUES ('Tail',262);
INSERT INTO part (name, weight) VALUES ('Left Wing',274);
INSERT INTO part (name, weight) VALUES ('Steam',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',274);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Right Wing',265);
INSERT INTO part (name, weight) VALUES ('Left Wing',265);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Forward',223);
INSERT INTO part (name, weight) VALUES ('Deck',223);
INSERT INTO part (name, weight) VALUES ('Head',246);
INSERT INTO part (name, weight) VALUES ('Deck',224);
INSERT INTO part (name, weight) VALUES ('Tail',167);
INSERT INTO part (name, weight) VALUES ('Deck',211);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Funnel',237);
INSERT INTO part (name, weight) VALUES ('Deck',257);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Steam',237);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Lower Back',262);
INSERT INTO part (name, weight) VALUES ('Bow',211);
INSERT INTO part (name, weight) VALUES ('Hull',173);
INSERT INTO part (name, weight) VALUES ('Hull',186);
INSERT INTO part (name, weight) VALUES ('Bow',223);
INSERT INTO part (name, weight) VALUES ('Propeller',257);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Deck',280);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',173);
INSERT INTO part (name, weight) VALUES ('Forward',186);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Forward',224);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Deck',223);
INSERT INTO part (name, weight) VALUES ('Upper Tail',237);
INSERT INTO part (name, weight) VALUES ('Right Wing',274);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Left Wing',167);
INSERT INTO part (name, weight) VALUES ('Bow',257);
INSERT INTO part (name, weight) VALUES ('Deck',223);
INSERT INTO part (name, weight) VALUES ('Hull',257);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Steam',262);
INSERT INTO part (name, weight) VALUES ('Left Wing',293);
INSERT INTO part (name, weight) VALUES ('Lower Back',265);
INSERT INTO part (name, weight) VALUES ('Hull',262);
INSERT INTO part (name, weight) VALUES ('Steam',262);
INSERT INTO part (name, weight) VALUES ('Upper Tail',211);
INSERT INTO part (name, weight) VALUES ('Tail',274);
INSERT INTO part (name, weight) VALUES ('Upper Tail',224);
INSERT INTO part (name, weight) VALUES ('Anchor',224);
INSERT INTO part (name, weight) VALUES ('Left Wing',224);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Forward',257);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Head',262);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Funnel',173);
INSERT INTO part (name, weight) VALUES ('Hull',280);
INSERT INTO part (name, weight) VALUES ('Bow',237);
INSERT INTO part (name, weight) VALUES ('Funnel',224);
INSERT INTO part (name, weight) VALUES ('Upper Tail',274);
INSERT INTO part (name, weight) VALUES ('Left Wing',265);
INSERT INTO part (name, weight) VALUES ('Right Wing',223);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Tail',262);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Upper Tail',223);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
INSERT INTO part (name, weight) VALUES ('Bow',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Propeller',223);
INSERT INTO part (name, weight) VALUES ('Head',274);
INSERT INTO part (name, weight) VALUES ('Propeller',224);
INSERT INTO part (name, weight) VALUES ('Deck',237);
INSERT INTO part (name, weight) VALUES ('Tail',246);
INSERT INTO part (name, weight) VALUES ('Propeller',173);
INSERT INTO part (name, weight) VALUES ('Hull',257);
INSERT INTO part (name, weight) VALUES ('Forward',173);
INSERT INTO part (name, weight) VALUES ('Anchor',186);
INSERT INTO part (name, weight) VALUES ('Hull',280);
INSERT INTO part (name, weight) VALUES ('Funnel',211);
INSERT INTO part (name, weight) VALUES ('Upper Tail',167);
INSERT INTO part (name, weight) VALUES ('Propeller',224);
INSERT INTO part (name, weight) VALUES ('Upper Back',246);
INSERT INTO part (name, weight) VALUES ('Bow',237);
INSERT INTO part (name, weight) VALUES ('Bow',274);
INSERT INTO part (name, weight) VALUES ('Left Wing',211);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Tail',173);
INSERT INTO part (name, weight) VALUES ('Lower Back',274);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',274);
INSERT INTO part (name, weight) VALUES ('Anchor',246);
INSERT INTO part (name, weight) VALUES ('Hull',223);
INSERT INTO part (name, weight) VALUES ('Lower Back',224);
INSERT INTO part (name, weight) VALUES ('Funnel',246);
INSERT INTO part (name, weight) VALUES ('Steam',280);
INSERT INTO part (name, weight) VALUES ('Right Wing',246);
INSERT INTO part (name, weight) VALUES ('Anchor',211);
INSERT INTO part (name, weight) VALUES ('Funnel',246);
INSERT INTO part (name, weight) VALUES ('Lower Back',224);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Lower Back',280);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Upper Tail',173);
INSERT INTO part (name, weight) VALUES ('Propeller',211);
INSERT INTO part (name, weight) VALUES ('Left Wing',211);
INSERT INTO part (name, weight) VALUES ('Head',211);
INSERT INTO part (name, weight) VALUES ('Funnel',262);
INSERT INTO part (name, weight) VALUES ('Upper Tail',257);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Head',223);
INSERT INTO part (name, weight) VALUES ('Lower Back',211);
INSERT INTO part (name, weight) VALUES ('Propeller',223);
INSERT INTO part (name, weight) VALUES ('Lower Back',274);
INSERT INTO part (name, weight) VALUES ('Propeller',257);
INSERT INTO part (name, weight) VALUES ('Upper Tail',223);
INSERT INTO part (name, weight) VALUES ('Hull',257);
INSERT INTO part (name, weight) VALUES ('Lower Back',224);
INSERT INTO part (name, weight) VALUES ('Bow',224);
INSERT INTO part (name, weight) VALUES ('Lower Back',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Deck',280);
INSERT INTO part (name, weight) VALUES ('Upper Tail',223);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Forward',257);
INSERT INTO part (name, weight) VALUES ('Hull',293);
INSERT INTO part (name, weight) VALUES ('Forward',173);
INSERT INTO part (name, weight) VALUES ('Head',237);
INSERT INTO part (name, weight) VALUES ('Propeller',274);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',237);
INSERT INTO part (name, weight) VALUES ('Anchor',186);
INSERT INTO part (name, weight) VALUES ('Tail',293);
INSERT INTO part (name, weight) VALUES ('Tail',265);
INSERT INTO part (name, weight) VALUES ('Upper Back',262);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Tail',224);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Anchor',173);
INSERT INTO part (name, weight) VALUES ('Anchor',293);
INSERT INTO part (name, weight) VALUES ('Propeller',167);
INSERT INTO part (name, weight) VALUES ('Anchor',293);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Anchor',274);
INSERT INTO part (name, weight) VALUES ('Lower Back',223);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Bow',274);
INSERT INTO part (name, weight) VALUES ('Steam',211);
INSERT INTO part (name, weight) VALUES ('Hull',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',293);
INSERT INTO part (name, weight) VALUES ('Head',280);
INSERT INTO part (name, weight) VALUES ('Lower Back',257);
INSERT INTO part (name, weight) VALUES ('Lower Back',224);
INSERT INTO part (name, weight) VALUES ('Deck',274);
INSERT INTO part (name, weight) VALUES ('Hull',211);
INSERT INTO part (name, weight) VALUES ('Steam',265);
INSERT INTO part (name, weight) VALUES ('Left Wing',262);
INSERT INTO part (name, weight) VALUES ('Propeller',293);
INSERT INTO part (name, weight) VALUES ('Left Wing',274);
INSERT INTO part (name, weight) VALUES ('Right Wing',257);
INSERT INTO part (name, weight) VALUES ('Upper Back',167);
INSERT INTO part (name, weight) VALUES ('Head',173);
INSERT INTO part (name, weight) VALUES ('Right Wing',173);
INSERT INTO part (name, weight) VALUES ('Tail',223);
INSERT INTO part (name, weight) VALUES ('Propeller',224);
INSERT INTO part (name, weight) VALUES ('Upper Back',224);
INSERT INTO part (name, weight) VALUES ('Tail',167);
INSERT INTO part (name, weight) VALUES ('Tail',173);
INSERT INTO part (name, weight) VALUES ('Upper Back',223);
INSERT INTO part (name, weight) VALUES ('Tail',265);
INSERT INTO part (name, weight) VALUES ('Lower Back',211);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Funnel',274);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Deck',237);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Head',274);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Right Wing',167);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Upper Tail',237);
INSERT INTO part (name, weight) VALUES ('Upper Back',224);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Deck',224);
INSERT INTO part (name, weight) VALUES ('Hull',224);
INSERT INTO part (name, weight) VALUES ('Left Wing',280);
INSERT INTO part (name, weight) VALUES ('Steam',265);
INSERT INTO part (name, weight) VALUES ('Head',265);
INSERT INTO part (name, weight) VALUES ('Forward',265);
INSERT INTO part (name, weight) VALUES ('Left Wing',211);
INSERT INTO part (name, weight) VALUES ('Deck',211);
INSERT INTO part (name, weight) VALUES ('Head',257);
INSERT INTO part (name, weight) VALUES ('Steam',167);
INSERT INTO part (name, weight) VALUES ('Head',167);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
INSERT INTO part (name, weight) VALUES ('Right Wing',224);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Tail',293);
INSERT INTO part (name, weight) VALUES ('Upper Tail',223);
INSERT INTO part (name, weight) VALUES ('Deck',246);
INSERT INTO part (name, weight) VALUES ('Tail',265);
INSERT INTO part (name, weight) VALUES ('Lower Back',293);
INSERT INTO part (name, weight) VALUES ('Propeller',293);
INSERT INTO part (name, weight) VALUES ('Deck',246);
INSERT INTO part (name, weight) VALUES ('Right Wing',274);
INSERT INTO part (name, weight) VALUES ('Hull',293);
INSERT INTO part (name, weight) VALUES ('Propeller',293);
INSERT INTO part (name, weight) VALUES ('Left Wing',293);
INSERT INTO part (name, weight) VALUES ('Bow',262);
INSERT INTO part (name, weight) VALUES ('Upper Back',293);
INSERT INTO part (name, weight) VALUES ('Anchor',237);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Head',167);
INSERT INTO part (name, weight) VALUES ('Hull',173);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Funnel',223);
INSERT INTO part (name, weight) VALUES ('Upper Tail',167);
INSERT INTO part (name, weight) VALUES ('Steam',211);
INSERT INTO part (name, weight) VALUES ('Steam',293);
INSERT INTO part (name, weight) VALUES ('Funnel',223);
INSERT INTO part (name, weight) VALUES ('Hull',262);
INSERT INTO part (name, weight) VALUES ('Anchor',224);
INSERT INTO part (name, weight) VALUES ('Steam',211);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Hull',246);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Lower Back',280);
INSERT INTO part (name, weight) VALUES ('Head',237);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Lower Back',265);
INSERT INTO part (name, weight) VALUES ('Forward',237);
INSERT INTO part (name, weight) VALUES ('Right Wing',280);
INSERT INTO part (name, weight) VALUES ('Funnel',224);
INSERT INTO part (name, weight) VALUES ('Tail',167);
INSERT INTO part (name, weight) VALUES ('Right Wing',211);
INSERT INTO part (name, weight) VALUES ('Anchor',237);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Bow',211);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Funnel',186);
INSERT INTO part (name, weight) VALUES ('Forward',186);
INSERT INTO part (name, weight) VALUES ('Tail',274);
INSERT INTO part (name, weight) VALUES ('Deck',262);
INSERT INTO part (name, weight) VALUES ('Forward',246);
INSERT INTO part (name, weight) VALUES ('Right Wing',274);
INSERT INTO part (name, weight) VALUES ('Right Wing',211);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Bow',237);
INSERT INTO part (name, weight) VALUES ('Steam',274);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',223);
INSERT INTO part (name, weight) VALUES ('Head',224);
INSERT INTO part (name, weight) VALUES ('Hull',186);
INSERT INTO part (name, weight) VALUES ('Left Wing',293);
INSERT INTO part (name, weight) VALUES ('Left Wing',237);
INSERT INTO part (name, weight) VALUES ('Upper Back',211);
INSERT INTO part (name, weight) VALUES ('Steam',246);
INSERT INTO part (name, weight) VALUES ('Funnel',223);
INSERT INTO part (name, weight) VALUES ('Lower Back',223);
INSERT INTO part (name, weight) VALUES ('Left Wing',265);
INSERT INTO part (name, weight) VALUES ('Hull',224);
INSERT INTO part (name, weight) VALUES ('Upper Tail',223);
INSERT INTO part (name, weight) VALUES ('Bow',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',224);
INSERT INTO part (name, weight) VALUES ('Right Wing',262);
INSERT INTO part (name, weight) VALUES ('Funnel',237);
INSERT INTO part (name, weight) VALUES ('Anchor',265);
INSERT INTO part (name, weight) VALUES ('Bow',237);
INSERT INTO part (name, weight) VALUES ('Head',167);
INSERT INTO part (name, weight) VALUES ('Funnel',293);
INSERT INTO part (name, weight) VALUES ('Deck',167);
INSERT INTO part (name, weight) VALUES ('Lower Back',167);
INSERT INTO part (name, weight) VALUES ('Head',186);
INSERT INTO part (name, weight) VALUES ('Forward',224);
INSERT INTO part (name, weight) VALUES ('Left Wing',265);
INSERT INTO part (name, weight) VALUES ('Upper Back',274);
INSERT INTO part (name, weight) VALUES ('Hull',257);
INSERT INTO part (name, weight) VALUES ('Deck',257);
INSERT INTO part (name, weight) VALUES ('Steam',211);
INSERT INTO part (name, weight) VALUES ('Upper Tail',265);
INSERT INTO part (name, weight) VALUES ('Hull',280);
INSERT INTO part (name, weight) VALUES ('Upper Back',186);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Lower Back',211);
INSERT INTO part (name, weight) VALUES ('Upper Tail',211);
INSERT INTO part (name, weight) VALUES ('Bow',186);
INSERT INTO part (name, weight) VALUES ('Anchor',173);
INSERT INTO part (name, weight) VALUES ('Funnel',173);
INSERT INTO part (name, weight) VALUES ('Deck',167);
INSERT INTO part (name, weight) VALUES ('Left Wing',224);
INSERT INTO part (name, weight) VALUES ('Steam',246);
INSERT INTO part (name, weight) VALUES ('Hull',237);
INSERT INTO part (name, weight) VALUES ('Funnel',274);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Funnel',223);
INSERT INTO part (name, weight) VALUES ('Upper Tail',186);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Deck',293);
INSERT INTO part (name, weight) VALUES ('Upper Back',237);
INSERT INTO part (name, weight) VALUES ('Bow',246);
INSERT INTO part (name, weight) VALUES ('Left Wing',237);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Anchor',280);
INSERT INTO part (name, weight) VALUES ('Tail',186);
INSERT INTO part (name, weight) VALUES ('Steam',265);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Forward',293);
INSERT INTO part (name, weight) VALUES ('Deck',167);
INSERT INTO part (name, weight) VALUES ('Bow',265);
INSERT INTO part (name, weight) VALUES ('Left Wing',173);
INSERT INTO part (name, weight) VALUES ('Head',211);
INSERT INTO part (name, weight) VALUES ('Lower Back',293);
INSERT INTO part (name, weight) VALUES ('Tail',246);
INSERT INTO part (name, weight) VALUES ('Funnel',246);
INSERT INTO part (name, weight) VALUES ('Steam',186);
INSERT INTO part (name, weight) VALUES ('Upper Back',280);
INSERT INTO part (name, weight) VALUES ('Upper Tail',274);
INSERT INTO part (name, weight) VALUES ('Anchor',257);
INSERT INTO part (name, weight) VALUES ('Steam',173);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Upper Tail',173);
INSERT INTO part (name, weight) VALUES ('Anchor',186);
INSERT INTO part (name, weight) VALUES ('Hull',167);
INSERT INTO part (name, weight) VALUES ('Deck',223);
INSERT INTO part (name, weight) VALUES ('Hull',280);
INSERT INTO part (name, weight) VALUES ('Left Wing',237);
INSERT INTO part (name, weight) VALUES ('Bow',293);
INSERT INTO part (name, weight) VALUES ('Upper Tail',237);
INSERT INTO part (name, weight) VALUES ('Hull',167);
INSERT INTO part (name, weight) VALUES ('Propeller',265);
INSERT INTO part (name, weight) VALUES ('Upper Back',262);
INSERT INTO part (name, weight) VALUES ('Hull',186);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Tail',265);
INSERT INTO part (name, weight) VALUES ('Deck',223);
INSERT INTO part (name, weight) VALUES ('Tail',257);
INSERT INTO part (name, weight) VALUES ('Tail',237);
INSERT INTO part (name, weight) VALUES ('Tail',211);
INSERT INTO part (name, weight) VALUES ('Hull',262);
INSERT INTO part (name, weight) VALUES ('Hull',167);
INSERT INTO part (name, weight) VALUES ('Steam',167);
INSERT INTO part (name, weight) VALUES ('Anchor',224);
INSERT INTO part (name, weight) VALUES ('Propeller',186);
INSERT INTO part (name, weight) VALUES ('Funnel',265);
INSERT INTO part (name, weight) VALUES ('Bow',265);
INSERT INTO part (name, weight) VALUES ('Steam',293);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Forward',257);
INSERT INTO part (name, weight) VALUES ('Deck',173);
INSERT INTO part (name, weight) VALUES ('Lower Back',265);
INSERT INTO part (name, weight) VALUES ('Propeller',224);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Hull',265);
INSERT INTO part (name, weight) VALUES ('Forward',167);
INSERT INTO part (name, weight) VALUES ('Propeller',257);
INSERT INTO part (name, weight) VALUES ('Left Wing',223);
INSERT INTO part (name, weight) VALUES ('Funnel',293);
INSERT INTO part (name, weight) VALUES ('Upper Back',224);
INSERT INTO part (name, weight) VALUES ('Bow',223);
INSERT INTO part (name, weight) VALUES ('Deck',186);
INSERT INTO part (name, weight) VALUES ('Propeller',167);
INSERT INTO part (name, weight) VALUES ('Right Wing',186);
INSERT INTO part (name, weight) VALUES ('Funnel',223);
INSERT INTO part (name, weight) VALUES ('Upper Back',257);
INSERT INTO part (name, weight) VALUES ('Lower Back',223);
INSERT INTO part (name, weight) VALUES ('Bow',262);
INSERT INTO part (name, weight) VALUES ('Propeller',274);
INSERT INTO part (name, weight) VALUES ('Head',293);
INSERT INTO part (name, weight) VALUES ('Forward',280);
INSERT INTO part (name, weight) VALUES ('Lower Back',293);
INSERT INTO part (name, weight) VALUES ('Head',167);
INSERT INTO part (name, weight) VALUES ('Propeller',274);
INSERT INTO part (name, weight) VALUES ('Left Wing',186);
